export const initUser = {
    username: "",
    email: "",
    role: "",
    fullName: "",
    userCourse: "",
    classId: "",
    majorId: "",
    departmentId: "",
    dateOfBirth: "",
    placeOfBirth: "",
    sex: true,
    phone: "",
    address: "",
    personalId: "",
};
