export const initSOSY = {
    subjectId: "",
    schoolYearId: "",
    classId: "",
    lecturerId: "",
    roomId: "",
    creditId: "",
    start: "",
    end: "",
    fromTime: "",
    toTime: "",
    timeStudyOfWeek: "",
    totalWeek: "",
    timeFinalExam: "",
    userCourse: "",
};
