export const routes = {
  HOME: '/',
  LOGIN: '/login',
  TUITION: '/tuition',
  COURSE_REGISTRATION: '/courses-registration',
  COURSE_REGISTRATION_DETAIL: '/courses-registration-detail',
  SCORE_RESULT: '/score-result',
  USER_PROFILE: '/user-profile',
  CHANGE_PASSWORD: '/change-password',
  SCHEDULE: '/schedule',
  TEST_SCHEDULE: '/test-schedule',
  LECTURER_HOME: '/lecturer/home',
  LECTURER_SCORE_INP: '/lecturer/score-inp',
  LECTURER_GET_CLASS: '/lecturer/get-class',
};
